// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCde9rL-1RTOvPpC6Y_9xXjhS3kY-XRwgM',
    appId: '1:960824864356:web:e9fc0c6f39c6196074b971',
    messagingSenderId: '960824864356',
    projectId: 'flutter-chatapp-c406a',
    authDomain: 'flutter-chatapp-c406a.firebaseapp.com',
    storageBucket: 'flutter-chatapp-c406a.firebasestorage.app',
    measurementId: 'G-30Y2VCT0QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--08ZAUGDSuLluONv-UOzdd0mtIs1Obw',
    appId: '1:960824864356:android:d5107a478e28988274b971',
    messagingSenderId: '960824864356',
    projectId: 'flutter-chatapp-c406a',
    storageBucket: 'flutter-chatapp-c406a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHFfoUY9McsGMvn_jsz03lJgy-0VG-IAc',
    appId: '1:960824864356:ios:e9ec6b63ea64026174b971',
    messagingSenderId: '960824864356',
    projectId: 'flutter-chatapp-c406a',
    storageBucket: 'flutter-chatapp-c406a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHFfoUY9McsGMvn_jsz03lJgy-0VG-IAc',
    appId: '1:960824864356:ios:e9ec6b63ea64026174b971',
    messagingSenderId: '960824864356',
    projectId: 'flutter-chatapp-c406a',
    storageBucket: 'flutter-chatapp-c406a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCde9rL-1RTOvPpC6Y_9xXjhS3kY-XRwgM',
    appId: '1:960824864356:web:f0d07e5dedd4d8a874b971',
    messagingSenderId: '960824864356',
    projectId: 'flutter-chatapp-c406a',
    authDomain: 'flutter-chatapp-c406a.firebaseapp.com',
    storageBucket: 'flutter-chatapp-c406a.firebasestorage.app',
    measurementId: 'G-T51EV04QB4',
  );
}
